[package]
name = "seam-carving"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
image = "0.24.8"
ordered-float = "4.2.0"
rand = "0.8.5"

[profile.release]
panic = "abort"
