[package]
name = "seam-carving"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.18", features = ["derive"] }
image = "0.24.8"
pbr = "1.1.1"

[profile.release]
panic = "abort"
